$(function(){
      var strHeader="",strVar = "",strBtm = "";
            strHeader += "<div class=\"header\"> \n";
            strHeader += "    <div class=\"header-box fn-clear\"> \n";
            strHeader += "     <div class=\"header-brand fn-left\"> \n";
            strHeader += "      <a href=\"./index.html\" class=\"brand-img\"> <img src=\"./images/logo.png\" alt=\"裕福集团\" /> <\/a> \n";
            strHeader += "     <\/div> \n";
            strHeader += "     <div class=\"header-nav\"> \n";
            strHeader += "      <div class=\"nav-menu fn-clear\">  \n";
            strHeader += "      <\/div>\n";
            strHeader += "     <\/div> \n";
            strHeader += "     <div class=\"nav-right fn-right\">  \n";
            strHeader += "      <div class=\"nav-lang\"> \n";
            strHeader += "       <ul class=\"lang-downlist\"> \n";
            strHeader += "        <li class=\"downlist-item  current\" data-value=\"zh-CN\"> <a class=\"item-link\">简<\/a> <\/li> \n";
            strHeader += "        <li class=\"downlist-item\" data-value=\"zh-TW\"> <a class=\"item-link\">繁<\/a> <\/li> \n";
            strHeader += "        <li class=\"downlist-item\" data-value=\"en\"> <a class=\"item-link\">EN<\/a> <\/li> \n";
            strHeader += "       <\/ul> \n";
            strHeader += "      <\/div> \n";
            strHeader += "     <\/div> \n";
            strHeader += "    <\/div> \n";
            strHeader += "   <\/div>\n";
            $(".global-header").html(strHeader);
            strVar += "<div class=\"nav-list\"> \n";
            strVar += "        <a href=\"./index.html\" class=\"nav-list-a i18n\" name=\"index\"><\/a> \n";
            strVar += "       <\/div> \n";
            strVar += "       <div class=\"nav-list\"> \n";
            strVar += "        <a href=\"javascript:;\" class=\"nav-list-a i18n\" name=\"AboutFu\"><\/a> \n";
            strVar += "        <ul class=\"nav-second\"> \n";
            strVar += "         <li> <a href=\"./brief.html\" class=\"i18n\" name=\"AF11\"><\/a> <\/li> \n";
            strVar += "         <li> <a href=\"./history.html\" class=\"i18n\" name=\"AF12\"><\/a> <\/li> \n";
            strVar += "         <li> <a href=\"./civilization.html\" class=\"i18n\" name=\"AF13\"><\/a> <\/li> \n";
            // strVar += "         <li> <a href=\"./honor.html\" class=\"i18n\" name=\"AF14\"><\/a> <\/li> \n";
            strVar += "        <\/ul> \n";
            strVar += "       <\/div> \n";
            strVar += "       <div class=\"nav-list\"> \n";
            strVar += "        <a href=\"javascript:;\" class=\"nav-list-a i18n\" name=\"YFindustry\"><\/a> \n";
            strVar += "        <ul class=\"nav-second\"> \n";
            strVar += "         <li> <a href=\"./industry.html?anchor=section1\" class=\"i18n\" name=\"AF21\"><\/a> <\/li> \n";
            strVar += "         <li> <a href=\"./industry.html?anchor=section2\" class=\"i18n\" name=\"AF22\"><\/a> <\/li> \n";
            strVar += "         <li> <a href=\"./industry.html?anchor=section3\" class=\"i18n\" name=\"AF23\"><\/a> <\/li> \n";
            strVar += "         <li> <a href=\"./industry.html?anchor=section4\" class=\"i18n\" name=\"AF24\"><\/a> <\/li> \n";
            strVar += "         <li> <a href=\"./industry.html?anchor=section5\" class=\"i18n\" name=\"AF25\"><\/a> <\/li> \n";
            strVar += "        <\/ul> \n";
            strVar += "       <\/div> \n";
            strVar += "       <div class=\"nav-list\"> \n";
            strVar += "        <a href=\"javascript:;\" class=\"nav-list-a i18n\" name=\"news\"><\/a> \n";
            strVar += "        <ul class=\"nav-second\"> \n";
            strVar += "         <li> <a href=\"./news.html\" class=\"i18n\" name=\"AF31\"><\/a> <\/li> \n";
            strVar += "        <\/ul> \n";
            strVar += "       <\/div> \n";
            strVar += "       <div class=\"nav-list\"> \n";
            strVar += "        <a href=\"javascript:;\" class=\"nav-list-a i18n\" name=\"contentUs\"><\/a> \n";
            strVar += "        <ul class=\"nav-second\"> \n";
            strVar += "         <li> <a href=\"./location.html\" class=\"i18n\" name=\"AF51\"><\/a> <\/li> \n";
            strVar += "        <\/ul> \n";
            strVar += "       <\/div>\n";
            $(".nav-menu,.friend-links").html(strVar);
            strBtm += "<div class=\"bottom-left fn-left\"> \n";
            strBtm += "       <div class=\"sns-links\"> \n";
            strBtm += "       <img src=\"./images/400.png\"/> &nbsp;\n";
            strBtm += "        400-000-8800\n";
            strBtm += "       <\/div> \n";
            strBtm += "      <\/div> \n";
            strBtm += "      <div class=\"bottom-right fn-right\"> \n";
            strBtm += "       <span class=\"copyright i18n\" name=\"copyright\"><\/span>\n";
            strBtm += "       <span class=\"i18n\" name=\"recordNumber\"><\/span> \n";
            strBtm += "      <\/div>\n";
            $(".footer-bottom").html(strBtm)
})